# Generated by Django 5.2.2 on 2025-06-14 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Record Date"),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True, null=True, verbose_name="Chief Complaint"
                    ),
                ),
                (
                    "current_symptoms",
                    models.TextField(
                        blank=True, null=True, verbose_name="Current Symptoms"
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "ordering": ["-record_date"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescription_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Prescription Date"
                    ),
                ),
                (
                    "medications",
                    models.TextField(
                        help_text="List medications with name, dosage, duration (e.g., 'Paracetamol 500mg, 1 tablet 3x/day for 5 days')",
                        verbose_name="Medications",
                    ),
                ),
                (
                    "complementary_exams",
                    models.TextField(
                        blank=True,
                        help_text="E.g., 'Blood work (CBC, Glucose)', 'Chest X-Ray'",
                        null=True,
                        verbose_name="Complementary Exams",
                    ),
                ),
                (
                    "medical_advice",
                    models.TextField(
                        blank=True,
                        help_text="E.g., 'Rest for 3 days', 'Low-sodium diet', 'Avoid strenuous activity'",
                        null=True,
                        verbose_name="Medical Advice/Instructions",
                    ),
                ),
                (
                    "is_signed",
                    models.BooleanField(default=True, verbose_name="Is Signed"),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "ordering": ["-prescription_date"],
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_date",
                    models.DateTimeField(verbose_name="Consultation Date"),
                ),
                ("diagnosis", models.TextField(verbose_name="Diagnosis")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Follow-up Date"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="users.customuser",
                        verbose_name="Consulting Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation",
                "verbose_name_plural": "Consultations",
                "ordering": ["-consultation_date"],
            },
        ),
        migrations.CreateModel(
            name="DiseaseEvolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evolution_date",
                    models.DateField(auto_now_add=True, verbose_name="Evolution Date"),
                ),
                ("observations", models.TextField(verbose_name="Observations")),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disease_evolution_entries",
                        to="users.customuser",
                        verbose_name="Observed By Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Evolution",
                "verbose_name_plural": "Disease Evolutions",
                "ordering": ["-evolution_date"],
            },
        ),
        migrations.CreateModel(
            name="HospitalizationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_date", models.DateField(verbose_name="Admission Date")),
                (
                    "discharge_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Discharge Date"
                    ),
                ),
                (
                    "reason_for_admission",
                    models.TextField(verbose_name="Reason for Admission"),
                ),
                (
                    "procedure_performed",
                    models.TextField(
                        blank=True, null=True, verbose_name="Procedure Performed"
                    ),
                ),
                ("report_details", models.TextField(verbose_name="Report Details")),
                (
                    "attending_doctor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospitalization_reports",
                        to="users.customuser",
                        verbose_name="Attending Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospitalization Report",
                "verbose_name_plural": "Hospitalization Reports",
                "ordering": ["-admission_date"],
            },
        ),
        migrations.CreateModel(
            name="ImagingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imaging_type",
                    models.CharField(
                        choices=[
                            ("xray", "X-Ray"),
                            ("ultrasound", "Ultrasound"),
                            ("mri", "MRI"),
                            ("ct_scan", "CT Scan"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Imaging Type",
                    ),
                ),
                ("scan_date", models.DateField(verbose_name="Scan Date")),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="imaging_results/",
                        verbose_name="Image File",
                    ),
                ),
                (
                    "report",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="imaging_reports/",
                        verbose_name="Report File (PDF)",
                    ),
                ),
                ("conclusion", models.TextField(verbose_name="Conclusion")),
                (
                    "radiologist",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imaging_readings",
                        to="users.customuser",
                        verbose_name="Radiologist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imaging Result",
                "verbose_name_plural": "Imaging Results",
                "ordering": ["-scan_date"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(max_length=100, verbose_name="Type of Analysis"),
                ),
                (
                    "measured_value",
                    models.CharField(max_length=255, verbose_name="Measured Value"),
                ),
                (
                    "reference_value",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Reference Value",
                    ),
                ),
                (
                    "conclusion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Biologist's Conclusion"
                    ),
                ),
                (
                    "sample_collection_date",
                    models.DateTimeField(verbose_name="Sample Collection Date"),
                ),
                (
                    "result_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Result Date"),
                ),
                (
                    "laboratory_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Laboratory Name",
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="lab_results/",
                        verbose_name="Result File (e.g., PDF)",
                    ),
                ),
                (
                    "technician_or_biologist",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type__in": ["staff", "doctor"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_test_entries",
                        to="users.customuser",
                        verbose_name="Technician/Biologist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratory Result",
                "verbose_name_plural": "Laboratory Results",
                "ordering": ["-result_date"],
            },
        ),
    ]
