# Generated by Django 5.2.2 on 2025-06-14 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medical_records", "0001_initial"),
        ("patients", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "user_type__in": ["doctor", "admin", "staff", "pharmacist"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.customuser",
                verbose_name="Recorded By",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_results",
                to="medical_records.medicalrecord",
                verbose_name="Medical Record",
            ),
        ),
        migrations.AddField(
            model_name="imagingresult",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imaging_results",
                to="medical_records.medicalrecord",
                verbose_name="Medical Record",
            ),
        ),
        migrations.AddField(
            model_name="hospitalizationreport",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospitalization_reports",
                to="medical_records.medicalrecord",
                verbose_name="Medical Record",
            ),
        ),
        migrations.AddField(
            model_name="diseaseevolution",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disease_evolutions",
                to="medical_records.medicalrecord",
                verbose_name="Medical Record",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="medical_records.medicalrecord",
                verbose_name="Medical Record",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions_made",
                to="users.customuser",
                verbose_name="Prescribing Doctor",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="medical_records.medicalrecord",
                verbose_name="Medical Record",
            ),
        ),
    ]
