# Generated by Django 5.0.14 on 2025-06-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="allergies",
            field=models.TextField(blank=True, null=True, verbose_name="Allergies"),
        ),
    ]
