# Generated by Django 5.2.2 on 2025-06-14 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name="Blood Group",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True,
                        help_text="E.g., allergies, chronic diseases",
                        null=True,
                        verbose_name="Medical History (Allergies, Chronic Diseases)",
                    ),
                ),
                (
                    "patient_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Patient ID",
                    ),
                ),
                (
                    "social_security_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Social Security Number",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        max_length=200, verbose_name="Emergency Contact Name"
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        max_length=20, verbose_name="Emergency Contact Phone"
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Emergency Contact Relationship",
                    ),
                ),
                (
                    "date_registered",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Registered"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_profile",
                        to="users.customuser",
                        verbose_name="Associated User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
